### ISSUE TITLE
擷取圖片連結過程卡住

### ISSUE THREAD

**Issue by ss919** [suzumiyahifumi/Fantia-Downloader-tampermonkey#1]
擷取圖片連結是有機率會卡住嗎？ 試了好幾個都常常卡在像是 27/28、18/22、20/24的的階段，甚至是已經成功打包下載過的貼文，我再按擷取一次還是有機率會卡住。本以為是圖片過多的文章才會遇到這問題，後來試了一個只有三張圖的也是卡在2/3不動XD

**Comment by suzumiyahifumi** [comment]
你是用哪個瀏覽器？版本號是多少？
你會遇到這種問題是在同一邊文章章內擷取第二次時會遇到的嗎？
-----------------------------
例如：
A圖片區
B圖片區
你先下載A區，OK
然後下載B區，出錯
(或是再次下載A區，出錯)
-----------------------------
有遇過一進文章下載第一次就出錯的狀況嗎？
我自己目前都沒有遇過這種問題。
希望你可以給我更詳細的狀況描述！謝謝

**Comment by suzumiyahifumi** [comment]
經過測試，建議使用 Firefox 安裝此腳本。
詳細問題可以看 README.md 內公告。
感謝使用此腳本與提醒問題。
如果可以幫助我修改請提供意見，我會非常感謝你。

**Comment by ss919** [comment]
用的是Chrome版本是89.0.4389.90 
不同篇文章和同一篇文章(即使剛才已經成功下載過一次)都有可能發生卡住的情形

拿 https://fan不知道能不能貼tia.jp/posts/625728 這篇來說
我付費區和免費區都試了7～8次了沒一次成功的
都會卡住

我目前觀察到的是這樣
希望多少能有當參考
