### ISSUE TITLE
1/18後 網站加載插件後無法顯示頁面，希望作能再解決

### ISSUE THREAD

**Issue by Blessmea** [suzumiyahifumi/Fantia-Downloader-tampermonkey#10]
這個工具非常好用，希望能繼續使用下去~

**Comment by suzumiyahifumi** [comment]
目前已經暫時修復一些功能。
Tampermonkey、FireFox extention 已經更新至 3.1.6

Some Bug has be fixed.
The Tampermonkey Script and FireFox extention has update to version 3.1.6.

Thank you for your reply.

**Comment by suzumiyahifumi** [comment]
If there are any bugs in version 3.1.6 still, this issue will be open back.
