### ISSUE TITLE
Fanta I 

### ISSUE THREAD

**Issue by e0972951006** [suzumiyahifumi/Fantia-Downloader-tampermonkey#2]
Can you download it for me https://fantia.jp/posts/135591 ?

**Comment by e0972951006** [comment]
https://fantia.jp/posts/210318

**Comment by e0972951006** [comment]
https://fantia.jp/posts/205729

**Comment by e0972951006** [comment]
@suzumiyahifumi 
Can you download it for me
https://fantia.jp/posts/205729
https://fantia.jp/posts/210318
https://fantia.jp/posts/135591 ?

**Comment by suzumiyahifumi** [comment]
I'm sorry, I can't download anything for you.
This script is for download your rewards which is buy by yourself.
You can use this script to download image after you pay something or support creator.

(I will close this issue by this reply)
